/* Auto-generated. Do not edit this file. */
window.test = window.test || {};
window.test.enums = window.test.enums || {};
window.test.Enum = function() {
	var self = this;
	self.descriptions = [];
   self.getDescription = function(val){ return self.descriptions[val]; };
   self.ids = [];
   self.getId = function(name){ return self.ids[name]; };
   self.map = [];
}
window.test.Enum.prototype.add = function(name, val, description) {
	var self = this;
	self[name] = val;
	self[val] = name;
	self.ids[val] = name;
	self.descriptions[val] = description;
   self.map.push({ id: val, name: name, description: description });
   return this;
}
window.test.enums.enumWithDescriptions = (new window.test.Enum())
	.add("multiWordEnumValue", 0, "Multi Word Enum Value")
	.add("moreComplexValue", 1, "More complex description!!1!")
	;
window.test.enums.includedEnum = (new window.test.Enum())
	.add("one", 0, "One")
	.add("two", 1, "Two")
	.add("three", 2, "Three")
	;
