/* Auto-generated. Do not edit this file. */
window.test = window.test || {};
window.test.enums = window.test.enums || [];
window.test.Enum = function() {
	this.__descriptions = [];
	this.__ids = [];
	this.__last_value = 0;
}
window.test.Enum.prototype.add = function(name, val) {
	if(val == undefined) val = ++this.__last_value;
	this[name] = val;
	this[val] = name;
	this.__ids[val] = name;
	this.__descriptions[val] = name.replace(/ShowWithEllipses$/,'...').replace(/([a-z])([A-Z])/g, '$1 $2').replace(/^\s+/,'');
    return this;
}
window.test.enums.IncludedEnum = (new Enum())
	.add("One", 0)
	.add("Two", 1)
	.add("Three", 2)
	;
